#!/usr/bin/ruby

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# => 4613732

max = 4_000_000
arr = [ 1, 2 ]

0.upto( max ) do | i |
	next_num = arr[ arr.length - 2 ] + arr[ arr.length - 1 ]
	next_num <= max ? arr.push( next_num ) : break
end

arr = arr.select { | num | num.even? }
sum = arr.reduce( :+ ) # Quick lil' hack to add 'em all together.

require './tester'
test( 2, sum )